export default [{
  name: '通栏广告',
  icon: 'statics/Hot/1.png',
  type_name: 'tl'
}, {
  name: 'QQ广告',
  icon: 'statics/Hot/2.png',
  type_name: 'qq'
}, {
  name: '商品广告',
  icon: 'statics/Hot/3.png',
  type_name: 'sp'
}, {
  name: '图文广告',
  icon: 'statics/Hot/4.png',
  type_name: 'tw'
}, {
  name: '名片广告',
  icon: 'statics/Hot/5.png',
  type_name: 'mp'
}, {
  name: '二维码广告',
  icon: 'statics/Hot/6.png',
  type_name: 'ewm'
}, {
  name: '电话广告',
  icon: 'statics/Hot/7.png',
  type_name: 'dh'
}, {
  name: 'APP广告',
  icon: 'statics/Hot/8.png',
  type_name: 'app'
}]
